site_name: Hello Robot  Documentation
site_url: https://docs.hello-robot.com
site_description: "Hello Robot User Documentation"
#repo_name: "github.com/hello-robot"
#repo_url: https://github.com/hello-robot

use_directory_urls: True
copyright: 'Copyright &copy; 2021 Hello Robot Inc'

theme:
 font: Arial
 name: material
 palette:
  - scheme: default
    primary: hello-robot-light
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  - scheme: slate
    primary: hello-robot-dark
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
 logo: images/hello_robot_logo_light.png
 favicon: images/hello_robot_favicon.png
extra_css:
  - extra.css
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/HelloRobotInc

nav:
 - Home: README.md
 - Resources:
   - Stretch Forum: "https://forum.hello-robot.com/"
   - Stretch GitHub: "https://github.com/hello-robot"
   - Stretch Videos: "https://youtube.com/c/HelloRobot"
edit_uri: ''



